sudo: required
services:
  - docker


before_install:
  - docker build -t sg-101/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true sg-101/docker-react npm run test


deploy:
   provider: elasticbeanstalk
   region: "us-west-2"
   app: "docker-react"
   env: "Docker-env"
   bucket: "elasticbeanstalk-us-west-2-234309483209" 
   bucket_path: "docker-react"
   on:
     branch: master

   access_key_id: 
     secure: "$AWS_ACCESS_KEY" 
   secret_access_key:
     secure: "$AWS_SECRET_KEY"
